# Generated by Django 6.0.3 on 2026-03-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='food',
            name='category',
            field=models.CharField(choices=[('protein', 'Protein'), ('cabohydrate', 'Carb'), ('vegetable', 'Veggie'), ('fruit', 'Fruit')], max_length=200),
        ),
    ]
